apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
spec:
  replicas: 3
  bootstrapServers: my-kafka-kafka-bootstrap:9092
  groupId: connect-cluster
  offsetStorageTopic: connect-offsets
  configStorageTopic: connect-configs
  statusStorageTopic: connect-status
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
  build:
    output:
      type: docker
    plugins:
      - name: rabbitmq-connector
        artifacts:
          - type: zip
            url: ../confluentinc-kafka-connect-rabbitmq-1.8.1.zip
