apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: kafka-consumer
  namespace: default
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  image: 10.0.1.56:5000/tensorflow-app:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark-apps/spark.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
  deps:
    jars:
      - local:///opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar

  executor:
    cores: 1
    instances: 4
    memory: 1g

