version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: "${HOSTNAME}"
    environment:
      RABBITMQ_ERLANG_COOKIE: "CLUSTERCOOKIE123"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
      RABBITMQ_NODENAME: "rabbit@${HOSTNAME}"
      RABBITMQ_USE_LONGNAME: "true"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    command: sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
