apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-kafka-connector
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq-kafka-connector
  template:
    metadata:
      labels:
        app: rabbitmq-kafka-connector
    spec:
      containers:
        - name: connector
          image: 10.0.1.56:5000/rabbitmq-kafka-connector:1.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-mqtt"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_BROKERS
              value: "rabbitmq-mqtt"
            - name: RABBITMQ_USER
              value: "davidra"
            - name: RABBITMQ_PASSWORD
              value: "davidra"
            - name: RABBITMQ_QUEUE
              value: "/cam/h264/#"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "input.images"
            - name: PREFETCH_COUNT
              value: "10"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
