apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-web-combo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-web-combo
  template:
    metadata:
      labels:
        app: kafka-web-combo
    spec:
      containers:
        - name: kafka-web-combo
          image: 10.0.1.56:5000/kafka-web-combo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "processed.frames"
            - name: GROUP_ID
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            # Dans le même conteneur, localhost pointe vers Flask
            - name: WEB_SERVER_URL
              value: "http://localhost:5000/api/data"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: web-disallowed
                operator: NotIn
                values:
                - "true"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-web-combo-svc
spec:
  selector:
    app: kafka-web-combo
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
